### ISSUE TITLE
Nothing is traced in VS output for core clr

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-aspnet5#68]

**Comment by olegsych** [comment]
That's done by `TelemetryClient` in Core, correct?

**Comment by abaranch** [comment]
Correct

**Comment by SergeyKanzhelev** [comment]
It may already be fixed by this change: 

**Debug logger included in ASP.NET 5 project templates**

The ASP.NET 5 project templates in Visual Studio now include the Debug logger by default so you can conveniently see logged messages in the Output window.

[Source](http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx)

**Comment by abaranch** [comment]
No, till it is fixed in Core: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Shared/Extensibility/Implementation/DebugOutput.cs

**Comment by SergeyKanzhelev** [comment]
I see events in debug output now.
